title: Mystorage
modelClass: Mcramirez\Mystorage\Models\Mystorage
list: $/mcramirez/mystorage/models/mystorage/columns.yaml
recordUrl: 'mcramirez/mystorage/mystorage/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
